import { Link } from "react-router-dom";

export default function Read() {
  return (
    <>
      <div className="container">
        {/* <!-- Outer Row --> */}
        <div className="row justify-content-center">
          <div className="col-xl-10 col-lg-12 col-md-9 ">
            <Link to="/" title="Back">
              <b className="backlink">
                <i class="fa-solid fa-arrow-left" style={{borderRadius:"50%",border:"3px solid black",padding:"3px"}}></i>
              </b>
            </Link>
            <div className="card o-hidden border-0 shadow-lg my-5">
              <p>
                Algorithmic trading software, often referred to as algo trading
                software, represents a pivotal advancement in financial markets.
                It leverages sophisticated algorithms to execute trades at
                speeds and frequencies impossible for human traders, offering
                efficiency and precision in market operations. By automating
                decision-making based on predefined strategies, algo trading
                software enables rapid analysis of vast amounts of market data,
                facilitating timely execution of trades across various asset
                classes. This technology not only enhances trading efficiency
                but also reduces human error and emotional bias, making it a
                cornerstone of modern financial strategies.
              </p>
              <p>
                All subscription fees paid to Algo is Non refundable. We do not
                provide trading tips nor we are investment adviser. Our service
                is solely restricted to automated trading application
                development, deployment and maintenance. All algorithms are
                based on backtested data but we do not provide any guarantee for
                their performance in future. The algorithm running in an
                automated system is agreed with the user prior deployment and we
                do not take any liability for any loss generated by the same.
                Past performance of advise/strategy/model does not indicate the
                future performance of any current or future strategy/model or
                advise by algofutureAlgo Trades and actual returns may differ
                significantly from that depicted herein due to various factors
                including but not limited to impact costs, expense charged,
                timing of entry/exit, timing of additional flows/redemptions,
                individual client mandates, specific portfolio construction
                characteristics etc. There is no assurance or guarantee that the
                objectives of any strategy/model or advice provided by
                algofutureAlgo Trades will be achieved. algofutureAlgo Trades or
                any of its partner/s or principal officer/employees do not
                assure/give guarantee for any return on the investment in
                strategies/models/advice given to the Investor. The value of
                investment can go up/down depending on factors & forces
                affecting securities markets. algofutureAlgo Trades or its
                associates are not liable or responsible for any loss or
                shortfall arising from operations and affected by the
                market condition.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
