import { Navigate, Outlet, Route, Routes } from "react-router-dom";
import Home from "./web/Home";
import About from "./web/About";
import Algo from "./web/Algo";
import Pricing from "./web/Pricing";
import Contact from "./web/Contact";
import ReadMore from "./web/ReadMore";
import Policy from "./web/Policies";
import { RegLoginCommon, Register, Login } from "./web/Login";
import WrongUser from "./web/WrongUser";
import WrongURL from "./web/WrongURL";
import AdminMain from "./admin/AdminMain";
import AdminDashboard from "./admin/AdminDashBoard";
import { useSelector } from "react-redux";
import Footer from "./Footer";
import { useEffect, useState } from "react";
import Popup from "./web/Popup";
import Confetti from 'react-confetti';
import { useWindowSize } from 'react-use';

export default function App() {
  const [showPopup, setShowPopup] = useState(false);
  const { width, height } = useWindowSize();
  useEffect(() => {
    // Trigger the popup when the component mounts
    setShowPopup(true);
  }, []);

  const closePopup = () => {
    setShowPopup(false);
  };
  return (
    <>
      {showPopup && <>
        <Popup message="You've won a prize!" onClose={closePopup} />
      </>}
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/about/" element={<About />} />
        <Route path="/algo" element={<Algo />} />
        <Route path="/pricing" element={<Pricing />} />
        <Route path="/contact" element={<Contact />} />
        <Route path="/readmore" element={<ReadMore />} />
        <Route path="/user/" element={<RegLoginCommon />}>
          <Route path="login" element={<Login />} />
          <Route path="register" element={<Register />} />
        </Route>
        <Route path="/wronguser" element={<WrongUser />} />
        <Route path="/admin/" element={<AdminPrivateRoute />}>
          <Route path="dashboard" element={<AdminDashboard />} />
        </Route>

        <Route path="/policy" element={<Policy />} />
        <Route path="*" element={<WrongURL />} />
      </Routes>

      <div className="footer_section layout_padding">
        <div className="container">
          <Footer />
          <div className="disclaimer_section">
            <div className="disclaimer_text">
              PROFITOLOGY is a sophisticated algotrading platform, uniquely
              integrated with TradingView and custom strategies, offering a
              seamless API connection to your broker. Tailored for retail
              traders and investors, our platform is dedicated to elevating
              wealth management practices. While we strive to ensure flawless
              operation, we recommend consulting a financial advisor before
              trading or investing through our platform. Please be aware that
              PROFITOLOGY cannot be held accountable for any losses resulting
              from market volatility or any platform-related issues. All
              subscription fees paid to Profitology Algo is Non refundable. We
              do not provide trading tips nor we are investment adviser. Our
              service is solely restricted to automated trading application
              development, deployment and maintenance. All algorithms are based
              on backtested data but we do not provide any guarantee for their
              performance in future. The algorithm running in an automated
              system is agreed with the user prior deployment and we do not take
              any liability for any loss generated by the same. Past performance
              of advise/strategy/model does not indicate the future performance
              of any current or future strategy/model or advise by Profitilogy
              Algo Trades and actual returns may differ significantly from that
              depicted herein due to various factors including but not limited
              to impact costs, expense charged, timing of entry/exit, timing of
              additional flows/redemptions, individual client mandates, specific
              portfolio construction characteristics etc. There is no assurance
              or guarantee that the objectives of any strategy/model or advice
              provided by Profitology Algo Trades will be achieved. Profitology
              Algo Trades or any of its partner/s or principal officer/employees
              do not assure/give guarantee for any return on the investment in
              strategies/models/advice given to the Investor. The value of
              investment can go up/down depending on factors & forces affecting
              securities markets. Profitology Algo Trades or its associates are
              not liable or responsible for any loss or shortfall arising from
              operations and affected by the market condition.
            </div>
          </div>
          <div className="copyright_section">
            <div className="copyright_text">
              Copyright 2024 All Right Reserved By{" "}
              <a href="http://www.techcoupling.in/" target="_blank">
                TechCoupling Solutions LLP
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

const AdminPrivateRoute = () => {
  const loginUserRole = useSelector((store) => store.user.value.role);
  return loginUserRole != undefined && loginUserRole == "admin" ? (
    <AdminMain />
  ) : (
    <Navigate to="/wronguser" />
  );
};

// const ClientPrivateRoute = ()=>
//   {
//       const loginUserRole = useSelector(store=>store.user.value.role)
//       return loginUserRole!=undefined && loginUserRole=='client' ? <AdminMain/> : <Navigate to="/wronguser"/>
//   }
